Repository yf-ivanguo/OctaPicks, pull requests merged in 2024-01, with the labels that each got.

#55 15 create taped stats features
  STATIC_UFC_FIGTERS.csv
  taped_stats.py
  webscrape.ipynb
Labels: feature

#49 3 create wl round features
  win_loss_round_feats.py
Labels: feature

#44 takedown feats
  takedown_feats.py
Labels: feature

#56 53 create testing files for each category
  clean_data.py
  tests/feature_creation_tests.py
  tests/test_fighters.csv
  tests/test_fights.csv
Labels: enhancement

#62 added changes to get_fighter_fights to fix returning empty df
  significant_strikes.py
  takedown_feats.py
  win_loss.py
Labels: bug

#67 frequency stats features
  frequency_stats_features.py
Labels: feature

#65 Added spatial_features.py
  spatial_features.py
Labels: feature

#66 win_loss_feats
  win_loss_stats_features.py
Labels: feature

#63 fight stats class
  fight_stats_features.py
Labels: feature
